### PR TITLE
SUPPORTENG-956_Updating authentication tests

### PR DESCRIPTION
**Pull request by marinahand**
Additional tests added to authentication.test.js

authentication.js test call modified to async

### CODE REVIEW

**Comment by marinahand** [comment]
@szchenghuang similar to [this older one](https://github.com/zapier/zapier-platform-example-app-github/pull/28), I'm looking for your approval to merge here, though for some reason it doesn't show you as a reviewer on this one, though it does for the repo itself.

**Review by szchenghuang — DISMISSED** [review]

**Comment by marinahand** [comment]
@szchenghuang thanks for the approval! I no longer have write access to the repo, could you merge this one or give me that access, whichever is simpler?

**Comment by rnegron** [comment]
@marinahand I invited you to join the `EPD: Dev Platform: Content` team. I'm thinking that should give you write access! Let me know if it does not work.

**Comment by marinahand** [comment]
@rnegron thanks! I committed some changes to match the feedback on this one: https://github.com/zapier/zapier-platform/pull/700 - once approved, I should be able to merge 🤞

**Review by rnegron — APPROVED** [review]

**Pull request merged**
